"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Auth_1 = require("./middleware/Auth");
const express_1 = require("express");
const CreateUserController_1 = require("./controllers/user/CreateUserController");
const FindUserController_1 = require("./controllers/user/FindUserController");
const FindByIdUserController_1 = require("./controllers/user/FindByIdUserController");
const DeleteUserController_1 = require("./controllers/user/DeleteUserController");
const UpdateUserController_1 = require("./controllers/user/UpdateUserController");
const LoginUserController_1 = require("./controllers/user/LoginUserController");
const GetProfileUserController_1 = require("./controllers/user/GetProfileUserController");
const createUserController = new CreateUserController_1.CreateUserController;
const findUserController = new FindUserController_1.FindUserController;
const findByIdUserController = new FindByIdUserController_1.FindByIdUserController;
const deleteUserController = new DeleteUserController_1.DeleteUserController;
const updateUserController = new UpdateUserController_1.UpdateUserController;
const loginUserController = new LoginUserController_1.LoginUserController;
const getProfileUserController = new GetProfileUserController_1.GetProfileUserController;
const router = (0, express_1.Router)();
router.post("/users", createUserController.create);
router.get("/users", findUserController.find);
router.get("/users/:id", findByIdUserController.findById);
router.delete("/users/:id", deleteUserController.delete);
router.put("/users/:id", updateUserController.update);
router.post("/login", loginUserController.login);
router.use(Auth_1.Auth);
router.get("/profile", getProfileUserController.getProfile);
exports.default = router;
